const planets = {
  Abafar: 'A desert planet located in the Outer Rim with a completely white surface. Known as The Void, the planet is barely populated but is home to massive amounts of rhydonium, a scarce and volatile fuel.',
  Agamar: 'A barren, rocky planet in the Outer Rim. Site of a still-active reserve of Separatist droids that became known for surviving the Clone Wars.',
  Ahch_To: 'Largely oceanic planet on which Luke Skywalker has been hiding for several years, and the location of the first Jedi Temple and the Tree Library of sacred Jedi texts. Porgs, Lanai and thala-sirens are among the native species.',
  Ajan_Kloss: 'A jungle moon which serves as a new base of operations for the Resistance. Years before, Leia and Luke were training there. Leia Organa dies here after using the last of her energy to reach out to her son through the Force.',
  Akiva: 'Jungle planet and home of Norra and Temmin Wexley, and a primary setting in Aftermath.',
  Alderaan: 'Forests, mountains; home planet of Princess Leia and the House of Organa. Destroyed by the first Death Star as punishment for involvement in the Rebel Alliance and also as a demonstration of power.',
  Aldhani: 'A temperate, alpine planet with highlands, valleys, forests, and lakes sacred to the indigenous Dhani people, until they were relocated by the Empire, having established a base situated within a dam housing a vault funding its military.',
  Aleen: 'A subterranean world located in the Mid Rim. The native species include, the surface-dwelling beings called the Aleena and sentient tree-like beings called Kindalo.',
  Alzoc_III: 'Ice planet, with many glaciers, and on its surface lies a crashed separatist carrier, with an anti-gravitational device.',
  Anaxes: 'A rocky planet located in the Azure sector of the galaxy&apos;s Core Worlds region. A majority of its surface was covered with tall, red plant-like life. In the early years of the Imperial Era, the planet was destroyed in a cataclysm, with the remains becoming the Anaxes asteroid belt.',
  Ando: 'A water-covered planet located in the Outer Rim, it is home to the amphibious Aqualish species and endures great turmoil during the Separatist Crisis.',
  Anoat: 'Polluted; A nearly inhospitable planet used by the Empire.',
  Atollon: 'Desert planet, site of Phoenix Squadron Rebel base. Home of the spider-like hexapods known as the Krykna, and the powerful force-wielder Bendu. The Battle of Atollon was allowed by Grand Admiral Thrawn himself, and destroyed most of the base, forcing the Phoenix Squadron to leave.',
  Barton_4: 'An icy planet where the Galactic Empire maintained a supply depot. The clone trooper CT-9904 "Crosshair" was sent to the outpost on the planet.',
  Balnab: 'A Barbaric world once visited by R2-D2 and C-3PO.',
  Batuu: 'A planet that features a remote frontier outpost and an old trading port.',
  Bespin: 'A gas planet with a thin layer of habitable atmosphere where Cloud City was located. The planet&apos;s gas layers were a source of rare tibanna gas which was harvested and refined at mining complexes like Cloud City.',
  Bogano: 'A largely uninhabited grassy planet in the Outer Rim, home to a Zeffo vault.',
  Bora_Vio: 'Located in the Lido system, this planet has a cloudy atmosphere and hosted a Kaminoan facility that was abandoned by the time of the Galactic Empire.',
  Bracca: 'An inhospitable junkyard planet in the Mid Rim considered strategically important in the Clone Wars. Becomes useful to the Scrapper Guild whose members salvage decommissioned ships for the Empire.',
  Brendok: 'A planet in the Outer Rim that is home to Osha and Mae Aniseya, as well as a coven of force-sensitive witches known as the Witches of Brendok.',
  Cantonica: 'An arid planet where the resort city of Canto Bight, home of the Canto Casino and Racetrack, is located.',
  Castilon: 'An ocean planet located in the Outer Rim near Wild Space. Home to the aircraft refueling station Colossus, as well as a destination for racers.',
  Cato_Neimoidia: 'Colony world of the Neimoidian species. The site of battles throughout the Clone Wars, notable for its "Bridge Cities". Also the site of Plo Koon&apos;s death during the Great Jedi Purge.',
  Chandrila: 'Homeworld of Mon Mothma and Ben Solo, it serves as the first capital of the New Republic. Serene planet known for calm seas and rolling hills.',
  Christophsis: 'During the Clone Wars, the Battle of Christophsis occurs here, serving as an introduction to Ahsoka Tano.',
  Concord_Dawn: 'Home planet of Jango Fett. Habitable planet that is surrounded by a large amount of debris from many vicious wars. Formerly controlled by the Mandalorians.',
  Corellia: 'Industrial planet located in the Core of the galaxy, with a strong culture of training pilots. Homeworld of Han Solo and Qi&apos;ra.',
  Coruscant: 'Cosmopolitan urban world consisting of one planet-wide city. Coruscant is situated in the heart of the Star Wars galaxy with a population of over one trillion, and is Governmental center of the Galactic Republic and later the Galactic Empire. Home to the main Jedi Temple.',
  Crait: 'Small mineral planet located in a remote section of the galaxy, its surface is covered with a layer of white salt over its red-colored soil. In Leia, Princess of Alderaan it is the location of an early Rebel Alliance outpost. Leia and her remaining Resistance forces flee there in The Last Jedi, where they face off with the First Order.',
  Daiyu: 'A cityscape planet where Ben Kenobi begins his search for Leia Organa.',
  D_Qar: 'Site of a Resistance operations base led by General Leia Organa.',
  Dagobah: 'Swamp planet and Yoda&apos;s residence after the fall of the Jedi.',
  Dantooine: 'Rural planet and the former site of a Rebel base. The writers of Rogue One considered depicting the Rebels evacuating the base for Yavin 4, but "it didn&apos;t move the story forward and it would have cost a ton of money."',
  Dathomir: 'Sith world and homeworld of the Nightsisters, including the Force-sensitive Asajj Ventress. Also the homeworld of the Zabrak warriors, including Darth Maul. A remote world, perpetually bathed in blood-red sunlight and home to numerous dangerous predators.',
  Devaron: 'Forest planet with an ancient Jedi Temple. Home to the horned Devaronian species.',
  Eadu: 'Rocky, mountainous planet beset by constant severe storms. Home to an Imperial weapons research facility. Its appearance was partly inspired by the fictitious planet LV-426 from the Alien franchise.',
  Endor: 'Blue gas giant with a complex planetary system, including moons like Sanctuary and Kef Bir, this system was controlled by the Empire until the second Death Star was destroyed.',
  Endor_Sanctuary: 'Forest moon that the second Death Star orbits, and house to an Imperial outpost. Inhabited by Ewoks. The location of the battle between the Rebel Alliance and the Empire leading to the destruction of the second Death Star.',
  Er_kit: 'Desert planet located in the galaxy&apos;s Outer Rim Territories. Homeworld of the Er&apos;Kit species.',
  Eriadu: 'Planet located in the galaxy&apos;s Outer Rim. Homeworld of Grand Moff Tarkin and his family.',
  Esseles: 'Under Imperial Control. The Empire has a listening post concealed in Esseles icy ring.',
  Exegol: 'A stormy planet in the galaxy&apos;s "Unknown Regions", with its location deliberately obscured by Republic and Jedi efforts. An ancient bastion of the Sith, it serves as the lair of Darth Sidious and the Sith Eternal during the construction of a Sith armada known as the Final Order.',
  Felucia: 'Jungle planet teeming with plants but little animal life. Aayla Secura is assassinated here during the Great Jedi Purge.',
  Ferrix: 'Desert planet with extensive scrapyard industry and known for its salvage markets.',
  Florrum: 'Sulfurous desert planet. Hondo Ohnaka is the leader of a pirate gang based on the planet.',
  Fondor: 'Imperial manufacturing center with large shipyards.',
  Geonosis: 'Rocky desert planet where battle droids are manufactured, and the site of the opening battle of the Clone Wars. All life on the planet is presumed destroyed by the Empire in Star Wars Rebels, with two exceptions: Klik-Klak and his offspring. Primary construction site of the first Death Star. Homeworld of the Geonosians.',
  Hosnian_Prime: 'Urban planet and capital of the New Republic. Destroyed by the First Order&apos;s Starkiller Base.',
  Hoth: 'Desolate ice planet and base for the Rebel Alliance.',
  Iego: 'An Outer Rim planet that harbors flying creatures called Xandu and medicinally important plants called Reeska. Iego is surrounded by 1000 moons and at least one of these, named Millius Prime, is home to a race called the Angels.',
  Ilum: 'Remote ice planet where kyber crystals are mined. Converted into Starkiller Base by the First Order and destroyed in The Force Awakens.',
  Iridonia: 'Home of the Iridonian Zabrak people and formerly rumored birthplace of Darth Maul.',
  Jabiim: 'A desert planet site of the Path, here Ben Kenobi help people to escape from the Empire.',
  Jakku: 'Desert planet. Site of a "graveyard" of ships damaged during the Battle of Jakku, the final battle between the New Republic and the Galactic Empire. Also the homeworld of Rey.',
  Jedha: 'Cold desert moon, and a sacred place for believers in the Force. A source of kyber crystals used for lightsabers and the Death Star&apos;s primary weapon. It is also the first location on which the Death Star&apos;s destructive capability is tested. Rogue One&apos;s director, Gareth Edwards, has described the location as "a Mecca or Jerusalem within the Star Wars world". It is also a homonym for Jeddah, the principal gateway to Mecca.',
  Jelucan: 'A rocky, mountainous planet in the Outer Rim, and the homeworld of Thane Kyrell and Ciena Ree.',
  Jestefad: 'A large gas planet that is part of the Mustafar system. Directly responsible for Mustafar&apos;s volcanic climate due to an intense gravitational tug-of-war with close by gas giant Lefrani.',
  Kamino: 'Ocean planet located outside the main galaxy, where cloning technology is developed and the Clone Army is created and trained. Obi-Wan Kenobi discovers that the planet is missing from the Jedi archives; it is later revealed to have been deleted as a part of the Sith plot to start the Clone Wars, and take over the galaxy.',
  Kashyyyk: 'Forest planet and home of the Wookiees. Also the site of one of the final battles of the Clone Wars.',
  Kef_Bir: 'A moon of Endor and the location of some of the wreckage of the second Death Star after it was destroyed in Return of the Jedi.',
  Kessel: 'A mining planet that has been fought over by crime lords for its valuable Spice. A fissure vent beneath the spice mines served as a source of astatic coaxium, an element that could be refined into hyperfuel for starships.',
  Khofar: 'A forest planet in the Outer Rim. Home to the Wookie Jedi Master Kelnacca.',
  Kijimi: 'A frigid mountainous planet and the homeworld of Zorii Bliss. Destroyed by the Xyston-class Star Destroyer Derriphan of the Sith Eternal&apos;s fleet, the Final Order.',
  Koboh: 'A rugged planet known for its abundance of the mineral priorite. Location of Rambler&apos;s Reach outpost.',
  Kuat: 'Industrial planet home to Kuat Drive Yards, the manufacturer of Star Destroyers.',
  Lah$mu: 'A remote planet with black sands, where Jyn Erso and her parents go into hiding.',
  Lothal: 'Remote farm planet and birthplace of Ezra Bridger.',
  Lotho_Minor: 'A planetary junkyard and hiding place of Darth Maul after his presumed death.',
  Malachor: 'Desolate Sith world and site of two major battles thousands of years apart, including a confrontation involving Darth Maul and several Rebels.',
  Malastare: 'Forested planet where podracing is popular. Birthplace of Sebulba and homeworld of the Dug.',
  Mandalore: 'Outer Rim planet that is the homeworld of the Mandalorians. Torn by wars between Mandalorians and Jedi, and later purged by the Empire. Has a moon, Concordia, which is fully inhabited.',
  Mapuzo: 'Desertified planet where Ben Kenobi and Leia Organa are hiding. Site of the first rematch between Kenobi and Vader.',
  Maridun: 'Grassy planet remaining undiscovered until the Clone Wars.',
  Mimban: 'Swamp planet with perpetual fog and overcast sky.',
  Mon_Cala: 'Ocean planet home to the Mon Calamari and Quarren species, also known as Mon Calamari or Dac.',
  Moraband: 'Home planet of ancient Sith lords, known as Korriban in Legends.',
  Mortis: 'Planet existing in the spiritual realm within the Force, home to the Mortis Gods.',
  Mustafar: 'Volcanic planet used by the Techno Union to mine valuable materials. Site of the duel between Anakin Skywalker and Obi-Wan Kenobi and Darth Vader&apos;s personal stronghold.',
  Mygeeto: 'Cold, urban planet and battle site in the final days of the Clone Wars. Colony world of the Muun species.',
  Naboo: 'Home planet of the Gungans and the Naboo, including Padmé Amidala and Palpatine.',
  Nal_Hutta: 'Home planet of Jabba and other Hutts, close to the urban moon of Nar Shaddaa.',
  Nevarro: 'Volcanic planet with black sands and lava flows. Hub of the Bounty Hunter Guild and home to a Mandalorian covert.',
  Niamos: 'Warm, sunny resort planet with pleasant beaches and calm waters. Under Imperial occupation, it is where Cassian Andor was arrested.',
  Numidian_Prime: 'Rainforest paradise and a haven to smugglers and thieves.',
  Nur: 'Water moon of Mustafar, base of Fortress Inquisitorius.',
  Oba_Diah: 'Location of the Pyke Syndicate&apos;s stronghold.',
  Olega: 'Planet where the Jedi Order operates a High Republic-era Jedi temple.',
  Onderon: 'Jungle planet where Anakin Skywalker and Ahsoka Tano lead a revolt against its Separatist-controlled usurpatory king. Birthplace of Saw Gerrera.',
  Ord_Mantell: 'Planet where Han Solo recounts a run-in with a bounty hunter.',
  Ossus: 'Verdant planet and home of Luke Skywalker&apos;s Jedi Temple.',
  Pasaana: 'Desert planet on the edge of the galaxy, home to the Aki-Aki species.',
  Pillio: 'Uncolonized aquatic planet with over 3 million species, and the location of one of Darth Sidious&apos; observatories.',
  Polis_Massa: 'Outer Rim planetoid within an asteroid field of the same name; birthplace of Luke Skywalker and Leia Organa.',
  Raada: 'Farming moon in the Outer Rim, where Ahsoka Tano hid under the name "Ashla" after Order 66.',
  Rishi: 'Tropical planet used by the Republic to monitor the nearby cloning facility on Kamino.',
  Rodia: 'Home planet of the Rodians, including Greedo. A remote swampy, jungle planet, it was represented by Onaconda Farr in the Galactic Senate during the Clone Wars.',
  Rugosa: 'A moon that consists of giant coral reefs. Yoda meets King Katuunko of the Toydarians here after being tested in battle by the Separatist Droid Army, during the early days of the Clone Wars. It is here where King Katuunko pledges Toydaria&apos;s allegiance to the Galactic Republic.',
  Ruusan: 'Barren planet housing the Valley of the Jedi. Site of a great battle between the Sith and the Jedi.',
  Ryloth: 'Dry, hot home planet of the Twi&apos;leks, including Hera Syndulla and Jedi Master Aayla Secura.',
  Saleucami: 'Primary terrain deserts and swamps. Home of the clone trooper deserter Cut Lawquane. Jedi Master Stass Allie is killed here during the Great Jedi Purge.',
  Savareen: 'Desert and ocean planet where destitute villages farm wind and refine coaxium. In Solo: A Star Wars Story, the Millennium Falcon arrives there after Han and his crew steal coaxium from Kessel, and Dryden Vos and Tobias Beckett die there.',
  Scarif: 'Oceanic "paradise world" used for construction of the Death Star after the project was moved from Geonosis during the Imperial Era. When Rebel Alliance members raid the Imperial database from the secret base on one of its tropical islands, the planet is destroyed to impede their escape with the Death Star plans.',
  Seatos: 'A forest planet with red-leaved trees. Location of the Reflex Point and where Morgan Elsbeth&apos;s ship, the Eye of Sion, is built.',
  Serenno: 'A planet in the Outer Rim Territories. Homeworld of Count Dooku.',
  Shili: 'Home planet of the Togruta, including Jedi Council member Shaak Ti and Padawan Ahsoka Tano.',
  Sissubo: 'Seventh Planet of the Chandrila system. It is surrounded by a debris field of remnants of Imperial Ships.',
  Skako_Minor: 'Home planet of Wat Tambor. Known for its highly pressurized atmosphere, necessitating specialized suits to be worn by all off-world Skakoans.',
  Sorgan: 'A forested backwater planet in the Outer Rim mostly populated by human farmers who harvest krill which is used to make spotchka, a popular drink on the planet. Local farmers are constantly attacked by Klatooinians.',
  Subterrel: 'Mining planet mentioned by Dexter Jettster who spent time prospecting there. Located near Kamino, beyond the Outer Rim.',
  Sullust: 'A volcanic planet whose atmosphere was highly toxic forcing the native Sullustans to build technologically advanced subterranean cities. It was the base of Imperial factories and the SoroSuub corporation employed roughly half the population.',
  Takodana: 'Forest planet and site of Maz Kanata&apos;s castle. Neutral territory between First Order and Resistance.',
  Tanalorr: 'A planet strong with the Force, hidden inside a nebula near Koboh. Home of Dagan Gera&apos;s Jedi Temple.',
  Tatooine: 'Desert planet and childhood home of Anakin Skywalker and Luke Skywalker. Location of Jabba the Hutt&apos;s palace.',
  Teth: 'During the Clone Wars, Jabba&apos;s son Rotta is abducted by the Separatists and brought to this planet. Anakin and Ahsoka Tano travel to Teth and rescue Rotta from Asajj Ventress.',
  Toydaria: 'Home planet of Watto and other Toydarians. Close to Nal Hutta.',
  Trandosha: 'Homeworld of the Trandoshan hunters. In the same solar system as Kashyyyk.',
  Ueda: 'Planet home to a village that contained the Lomi Usqi Noodle Shop.',
  Umbara: 'Planet with a thick, foggy atmosphere. Home to the Umbarans.',
  Utapau: 'Remote planet, covered in deep sinkholes and home to the Utai and Pau&apos;ans. Site of General Grievous&apos; death and a separatist base during the last days of the Clone Wars.',
  Vandor_1: 'Icy, mountainous planet that is the site of a Crimson Dawn train heist led by Tobias Beckett in Solo: A Star Wars Story.',
  Vardos: 'Imperial stronghold and home to Iden and Garrick Versio. One of the first targets of Operation: Cinder.',
  Wobani: 'A desolate wasteland and the site of an Imperial penal labor colony.',
  Wrea: 'A planet near an asteroid field where Saw Gerrara raises Jyn Erso after her father is taken by the Empire.',
  Yavin: 'Gas planet with several moons, including Yavin 4.',
  Yavin_4: 'Forest moon and base for the Rebel Alliance.',
  Zeffo: 'A planet with many mountains and stormy weather. Featuring ancient ruins and tombs, imperial excavations, and a crashed Venator near an ancient tomb.',
  Zygerria: 'A planet in the Outer Rim Territories home of the Zygerrian species. Zygerria was also known for a slave empire.',
};

export default planets;
